### PR TITLE
Fix registry-proxies flag

### PR DESCRIPTION
**Pull request by miguelbernadi**
Change-Id: Ie82c2558bc48974d1b0868b375f4c4dedb4acab3

### CODE REVIEW

**Review by joaoqalves — APPROVED** [review]

**Comment by joaoqalves** [comment]
@miguelbernadi Is there a way to have a test and avoid this from happening for other flags?

**Comment by miguelbernadi** [comment]
I can't think of a way to do that off the top of my head. We'd need to test it externally (by supplying a value to the flag) and verify the internal variable gets modified. This is quite close to testing the `flag` package directly in my POV.

This should be flagged by the compiler as a non-utilised variable. It's not, because we initialize the variable, assign it a value and then pass it forward. So if it is not used it stiln has the default value. If we changed to initialise and assign the variable in the same step, this kind of mistake would be a compiler error. I'm not clear on the downsides of that approach as I can't spot any right away. I'm referring to using `flag.String` instead of `flag.StringVar`.

**Review by tjamet — APPROVED** [review]

**Review by InsomniaCoder — APPROVED** [review]
I'm a bit lost on what was problem caused by this wrong flag. It'd be nice to have some reference 🙏🏼

**Comment by miguelbernadi** [comment]
> I'm a bit lost on what was problem caused by this wrong flag. It'd be nice to have some reference 🙏🏼

When I found the issue, there was no problem, as we were not using the flag, but it was obviously incorrect, so the fix had no description.

Right now, the problem would be that there is a will to use this flag, which was only possible after.

**Pull request merged**
